export const ResumeActionType = {
  ENROLL_INFO: 'ENROLL_INFO',
  TEMP_INFO: 'TEMP_INFO',
  SETTED_TEMP_INFO: 'SETTED_TEMP_INFO',
  CANCEL_INFO: 'CANCEL_INFO',
};

export const AlertActionType = {
  OPEN_ALERT: 'OPEN_ALERT',
  CLOSE_ALERT: 'CLOSE_ALERT',
};

export const ModalActionType = {
  OPEN_MODAL: 'OPEN_MODAL',
  CLOSE_MODAL: 'CLSOE_MODAL',
};

export const CommunicationType = {
  SIGN_UP: 'SIGN_UP',
  SIGN_IN: 'SGIN_IN',
  VIEW_INFO: 'VIEW_INFO',
  GET_INFO: 'GET_INFO',
  MODIFY_INFO: 'MODIFY_INFO',
  WITHDRWAL_INFO: 'WITHDRWAL_INFO',

  VIEW_RESUME: 'VIEW_RESUME',
  GET_RESUME: 'GET_RESUME',
  STORE_RESUME: 'STORE_RESUME',
  REMOVE_RESUME: 'REMOVE_RESUME',

  VIEW_TEMP_RESUME: 'VIEW_TEMP_RESUME',
  STORE_TEMP_RESUME: 'STORE_TEMP_RESUME',
  GET_TEMP_RESUME: 'GET_TEMP_RESUME',
};
